// Predetermined list of skills for the platform
// This list is shared between clients (task creation) and freelancers (profile skills)

export const PREDETERMINED_SKILLS = [
    // Web Development
    'JavaScript',
    'TypeScript',
    'React',
    'Vue.js',
    'Angular',
    'Node.js',
    'Express.js',
    'Next.js',
    'HTML',
    'CSS',
    'Tailwind CSS',
    'Bootstrap',
    'PHP',
    'Laravel',
    'WordPress',
    'Python',
    'Django',
    'Flask',
    'Ruby',
    'Ruby on Rails',
    'Java',
    'Spring Boot',
    'C#',
    '.NET',
    'ASP.NET',
    'SQL',
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Redis',
    'GraphQL',
    'REST API',
    'Git',
    'Docker',
    'Kubernetes',
    'AWS',
    'Azure',
    'Google Cloud',

    // Mobile Development
    'iOS Development',
    'Android Development',
    'React Native',
    'Flutter',
    'Swift',
    'Kotlin',
    'Xamarin',

    // Design
    'UI/UX Design',
    'Graphic Design',
    'Adobe Photoshop',
    'Adobe Illustrator',
    'Adobe XD',
    'Figma',
    'Sketch',
    'InDesign',
    'After Effects',
    'Premiere Pro',
    '3D Modeling',
    'Blender',
    'Maya',
    'Animation',
    'Video Editing',
    'Logo Design',
    'Brand Identity',
    'Web Design',
    'Mobile App Design',

    // Writing & Content
    'Content Writing',
    'Copywriting',
    'Technical Writing',
    'Blog Writing',
    'SEO Writing',
    'Creative Writing',
    'Proofreading',
    'Editing',
    'Ghostwriting',
    'Scriptwriting',
    'Translation',

    // Marketing & Business
    'Digital Marketing',
    'SEO',
    'SEM',
    'Social Media Marketing',
    'Email Marketing',
    'Content Marketing',
    'Google Analytics',
    'Facebook Ads',
    'Google Ads',
    'Marketing Strategy',
    'Brand Strategy',
    'Market Research',
    'Business Analysis',
    'Project Management',
    'Product Management',
    'Agile',
    'Scrum',

    // Data & Analytics
    'Data Analysis',
    'Data Science',
    'Machine Learning',
    'Artificial Intelligence',
    'Deep Learning',
    'Data Visualization',
    'Tableau',
    'Power BI',
    'Excel',
    'R',
    'MATLAB',
    'Statistics',

    // Other
    'Customer Service',
    'Virtual Assistant',
    'Accounting',
    'Bookkeeping',
    'Legal',
    'Consulting',
    'Research',
    'Testing',
    'QA',
    'DevOps',
    'Cybersecurity',
    'Blockchain',
    'Game Development',
    'Unity',
    'Unreal Engine',
].sort(); // Sort alphabetically for better UX
